[2023-04-27T00:00:08.766+0000] {processor.py:153} INFO - Started process (PID=60260) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:00:08.766+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:00:08.767+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:00:08.766+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:00:08.776+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:00:08.776+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:00:08.776+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:00:08.776+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:00:08.776+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:00:08.782+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2023-04-27T00:00:51.989+0000] {processor.py:153} INFO - Started process (PID=60495) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:00:51.991+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:00:51.991+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:00:51.991+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:00:52.001+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:00:52.001+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:00:52.001+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:00:52.001+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:00:52.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:00:52.008+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:01:31.859+0000] {processor.py:153} INFO - Started process (PID=60546) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:01:31.860+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:01:31.860+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:01:31.860+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:01:31.870+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:01:31.870+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:01:31.870+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:01:31.870+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:01:31.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:01:31.876+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:02:09.047+0000] {processor.py:153} INFO - Started process (PID=60681) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:02:09.048+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:02:09.048+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:02:09.048+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:02:09.058+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:02:09.058+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:02:09.059+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:02:09.059+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:02:09.059+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:02:09.065+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:02:45.022+0000] {processor.py:153} INFO - Started process (PID=60784) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:02:45.023+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:02:45.023+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:02:45.023+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:02:45.033+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:02:45.032+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:02:45.033+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:02:45.033+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:02:45.033+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:02:45.039+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:03:23.852+0000] {processor.py:153} INFO - Started process (PID=60832) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:03:23.853+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:03:23.854+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:03:23.854+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:03:23.864+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:03:23.864+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:03:23.864+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:03:23.864+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:03:23.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:03:23.870+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:04:08.248+0000] {processor.py:153} INFO - Started process (PID=60948) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:04:08.249+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:04:08.249+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:04:08.249+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:04:08.259+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:04:08.259+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:04:08.259+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:04:08.259+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:04:08.259+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:04:08.266+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:04:45.950+0000] {processor.py:153} INFO - Started process (PID=61055) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:04:45.951+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:04:45.951+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:04:45.951+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:04:45.961+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:04:45.961+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:04:45.961+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:04:45.961+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:04:45.962+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:04:45.968+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:05:20.912+0000] {processor.py:153} INFO - Started process (PID=61222) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:05:20.913+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:05:20.914+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:05:20.914+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:05:20.924+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:05:20.923+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:05:20.924+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:05:20.924+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:05:20.924+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:05:20.929+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:05:56.876+0000] {processor.py:153} INFO - Started process (PID=61325) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:05:56.877+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:05:56.878+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:05:56.878+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:05:56.888+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:05:56.888+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:05:56.888+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:05:56.888+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:05:56.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:05:56.894+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:06:39.086+0000] {processor.py:153} INFO - Started process (PID=61400) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:06:39.087+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:06:39.087+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:06:39.087+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:06:39.097+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:06:39.097+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:06:39.097+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:06:39.097+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:06:39.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:06:39.103+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:07:18.216+0000] {processor.py:153} INFO - Started process (PID=61553) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:07:18.217+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:07:18.218+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:07:18.218+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:07:18.228+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:07:18.227+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:07:18.228+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:07:18.228+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:07:18.228+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:07:18.233+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:08:00.220+0000] {processor.py:153} INFO - Started process (PID=61664) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:08:00.221+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:08:00.222+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:08:00.222+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:08:00.232+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:08:00.231+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:08:00.232+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:08:00.232+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:08:00.232+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:08:00.237+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:08:34.020+0000] {processor.py:153} INFO - Started process (PID=61710) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:08:34.021+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:08:34.022+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:08:34.022+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:08:34.032+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:08:34.031+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:08:34.032+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:08:34.032+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:08:34.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:08:34.038+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:09:12.946+0000] {processor.py:153} INFO - Started process (PID=61818) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:09:12.947+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:09:12.947+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:09:12.947+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:09:12.957+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:09:12.956+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:09:12.957+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:09:12.957+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:09:12.957+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:09:12.962+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:09:50.040+0000] {processor.py:153} INFO - Started process (PID=61929) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:09:50.041+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:09:50.041+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:09:50.041+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:09:50.051+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:09:50.050+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:09:50.051+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:09:50.051+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:09:50.051+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:09:50.056+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:10:39.174+0000] {processor.py:153} INFO - Started process (PID=62095) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:10:39.175+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:10:39.176+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:10:39.176+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:10:39.186+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:10:39.186+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:10:39.186+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:10:39.186+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:10:39.186+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:10:39.192+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:11:19.076+0000] {processor.py:153} INFO - Started process (PID=62193) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:11:19.077+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:11:19.077+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:11:19.077+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:11:19.087+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:11:19.087+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:11:19.088+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:11:19.088+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:11:19.088+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:11:19.094+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:11:56.746+0000] {processor.py:153} INFO - Started process (PID=62331) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:11:56.747+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:11:56.748+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:11:56.748+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:11:56.758+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:11:56.757+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:11:56.758+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:11:56.758+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:11:56.758+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:11:56.764+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:12:32.722+0000] {processor.py:153} INFO - Started process (PID=62377) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:12:32.723+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:12:32.724+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:12:32.724+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:12:32.734+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:12:32.733+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:12:32.734+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:12:32.734+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:12:32.734+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:12:32.740+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T00:13:13.781+0000] {processor.py:153} INFO - Started process (PID=62489) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:13:13.782+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:13:13.783+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:13:13.783+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:13:13.793+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:13:13.792+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:13:13.793+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:13:13.793+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:13:13.793+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:13:13.799+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:13:47.496+0000] {processor.py:153} INFO - Started process (PID=62591) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:13:47.498+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:13:47.498+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:13:47.498+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:13:47.508+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:13:47.508+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:13:47.508+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:13:47.508+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:13:47.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:13:47.514+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:14:27.125+0000] {processor.py:153} INFO - Started process (PID=62676) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:14:27.127+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:14:27.127+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:14:27.127+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:14:27.137+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:14:27.136+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:14:27.137+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:14:27.137+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:14:27.137+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:14:27.143+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:14:59.933+0000] {processor.py:153} INFO - Started process (PID=62810) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:14:59.934+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:14:59.935+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:14:59.935+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:14:59.945+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:14:59.944+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:14:59.945+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:14:59.945+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:14:59.945+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:14:59.951+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:15:37.783+0000] {processor.py:153} INFO - Started process (PID=62956) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:15:37.784+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:15:37.784+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:15:37.784+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:15:37.794+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:15:37.793+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:15:37.794+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:15:37.794+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:15:37.794+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:15:37.800+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:16:16.327+0000] {processor.py:153} INFO - Started process (PID=63077) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:16:16.328+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:16:16.328+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:16:16.328+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:16:16.338+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:16:16.338+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:16:16.338+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:16:16.338+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:16:16.338+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:16:16.344+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:16:56.200+0000] {processor.py:153} INFO - Started process (PID=63362) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:16:56.201+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:16:56.201+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:16:56.201+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:16:56.211+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:16:56.210+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:16:56.211+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:16:56.211+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:16:56.211+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:16:56.217+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:17:33.303+0000] {processor.py:153} INFO - Started process (PID=63657) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:17:33.304+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:17:33.304+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:17:33.304+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:17:33.314+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:17:33.314+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:17:33.314+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:17:33.314+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:17:33.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:17:33.321+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:18:12.123+0000] {processor.py:153} INFO - Started process (PID=63930) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:18:12.124+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:18:12.125+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:18:12.124+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:18:12.134+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:18:12.134+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:18:12.134+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:18:12.134+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:18:12.134+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:18:12.141+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:18:49.232+0000] {processor.py:153} INFO - Started process (PID=64208) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:18:49.233+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:18:49.233+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:18:49.233+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:18:49.243+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:18:49.243+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:18:49.243+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:18:49.243+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:18:49.243+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:18:49.249+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:19:28.675+0000] {processor.py:153} INFO - Started process (PID=64492) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:19:28.676+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:19:28.677+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:19:28.677+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:19:28.687+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:19:28.686+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:19:28.687+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:19:28.687+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:19:28.687+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:19:28.693+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:20:16.432+0000] {processor.py:153} INFO - Started process (PID=64927) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:20:16.433+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:20:16.434+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:20:16.434+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:20:16.444+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:20:16.443+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:20:16.444+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:20:16.444+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:20:16.444+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:20:16.449+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:20:51.566+0000] {processor.py:153} INFO - Started process (PID=65187) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:20:51.567+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:20:51.567+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:20:51.567+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:20:51.579+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:20:51.578+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:20:51.579+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:20:51.579+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:20:51.579+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:20:51.584+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T00:21:29.147+0000] {processor.py:153} INFO - Started process (PID=65456) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:21:29.148+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:21:29.149+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:21:29.149+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:21:29.159+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:21:29.158+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:21:29.159+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:21:29.159+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:21:29.159+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:21:29.164+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:22:06.366+0000] {processor.py:153} INFO - Started process (PID=65602) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:22:06.367+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:22:06.367+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:22:06.367+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:22:06.377+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:22:06.376+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:22:06.377+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:22:06.377+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:22:06.377+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:22:06.382+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:22:45.510+0000] {processor.py:153} INFO - Started process (PID=65796) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:22:45.512+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:22:45.512+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:22:45.512+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:22:45.522+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:22:45.522+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:22:45.522+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:22:45.522+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:22:45.522+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:22:45.528+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:23:21.665+0000] {processor.py:153} INFO - Started process (PID=65998) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:23:21.667+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:23:21.667+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:23:21.667+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:23:21.677+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:23:21.676+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:23:21.677+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:23:21.677+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:23:21.677+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:23:21.683+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:23:57.704+0000] {processor.py:153} INFO - Started process (PID=66142) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:23:57.705+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:23:57.706+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:23:57.705+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:23:57.715+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:23:57.714+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:23:57.715+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:23:57.715+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:23:57.715+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:23:57.721+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:24:38.595+0000] {processor.py:153} INFO - Started process (PID=66246) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:24:38.597+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:24:38.597+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:24:38.597+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:24:38.607+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:24:38.606+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:24:38.607+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:24:38.607+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:24:38.607+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:24:38.612+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:25:23.135+0000] {processor.py:153} INFO - Started process (PID=66441) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:25:23.136+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:25:23.136+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:25:23.136+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:25:23.146+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:25:23.146+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:25:23.146+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:25:23.146+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:25:23.146+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:25:23.152+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:26:04.006+0000] {processor.py:153} INFO - Started process (PID=66497) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:26:04.007+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:26:04.008+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:26:04.008+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:26:04.018+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:26:04.017+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:26:04.018+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:26:04.018+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:26:04.018+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:26:04.023+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:26:41.675+0000] {processor.py:153} INFO - Started process (PID=66556) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:26:41.676+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:26:41.676+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:26:41.676+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:26:41.685+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:26:41.685+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:26:41.686+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:26:41.686+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:26:41.686+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:26:41.691+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:27:17.479+0000] {processor.py:153} INFO - Started process (PID=66627) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:27:17.480+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:27:17.481+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:27:17.481+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:27:17.490+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:27:17.490+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:27:17.490+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:27:17.490+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:27:17.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:27:17.496+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:27:56.651+0000] {processor.py:153} INFO - Started process (PID=66735) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:27:56.652+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:27:56.653+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:27:56.653+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:27:56.662+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:27:56.662+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:27:56.663+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:27:56.663+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:27:56.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:27:56.668+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:28:37.820+0000] {processor.py:153} INFO - Started process (PID=66881) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:28:37.821+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:28:37.821+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:28:37.821+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:28:37.831+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:28:37.831+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:28:37.831+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:28:37.831+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:28:37.831+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:28:37.837+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:29:13.482+0000] {processor.py:153} INFO - Started process (PID=66955) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:29:13.483+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:29:13.484+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:29:13.483+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:29:13.493+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:29:13.493+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:29:13.493+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:29:13.493+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:29:13.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:29:13.499+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:29:56.536+0000] {processor.py:153} INFO - Started process (PID=67010) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:29:56.537+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:29:56.538+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:29:56.538+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:29:56.548+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:29:56.547+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:29:56.548+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:29:56.548+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:29:56.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:29:56.554+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:30:42.488+0000] {processor.py:153} INFO - Started process (PID=67184) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:30:42.489+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:30:42.490+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:30:42.489+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:30:42.500+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:30:42.499+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:30:42.500+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:30:42.500+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:30:42.500+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:30:42.505+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:31:21.957+0000] {processor.py:153} INFO - Started process (PID=67229) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:31:21.958+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:31:21.958+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:31:21.958+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:31:21.968+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:31:21.968+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:31:21.968+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:31:21.968+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:31:21.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:31:21.974+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:31:56.685+0000] {processor.py:153} INFO - Started process (PID=67301) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:31:56.686+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:31:56.686+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:31:56.686+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:31:56.696+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:31:56.696+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:31:56.696+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:31:56.696+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:31:56.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:31:56.702+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:32:30.385+0000] {processor.py:153} INFO - Started process (PID=67375) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:32:30.386+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:32:30.386+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:32:30.386+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:32:30.396+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:32:30.396+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:32:30.396+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:32:30.396+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:32:30.397+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:32:30.402+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:33:13.145+0000] {processor.py:153} INFO - Started process (PID=67429) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:33:13.146+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:33:13.146+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:33:13.146+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:33:13.156+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:33:13.155+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:33:13.156+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:33:13.156+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:33:13.156+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:33:13.162+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:33:55.460+0000] {processor.py:153} INFO - Started process (PID=67481) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:33:55.461+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:33:55.461+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:33:55.461+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:33:55.471+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:33:55.471+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:33:55.471+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:33:55.471+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:33:55.471+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:33:55.477+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:34:37.215+0000] {processor.py:153} INFO - Started process (PID=67540) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:34:37.216+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:34:37.217+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:34:37.217+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:34:37.227+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:34:37.227+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:34:37.227+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:34:37.227+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:34:37.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:34:37.233+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:35:21.305+0000] {processor.py:153} INFO - Started process (PID=67696) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:35:21.306+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:35:21.307+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:35:21.306+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:35:21.316+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:35:21.316+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:35:21.317+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:35:21.317+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:35:21.317+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:35:21.322+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:36:02.872+0000] {processor.py:153} INFO - Started process (PID=67748) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:36:02.874+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:36:02.874+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:36:02.874+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:36:02.883+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:36:02.883+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:36:02.883+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:36:02.883+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:36:02.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:36:02.889+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:36:40.806+0000] {processor.py:153} INFO - Started process (PID=67811) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:36:40.807+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:36:40.807+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:36:40.807+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:36:40.818+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:36:40.817+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:36:40.818+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:36:40.818+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:36:40.818+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:36:40.823+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:37:18.256+0000] {processor.py:153} INFO - Started process (PID=67884) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:37:18.257+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:37:18.258+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:37:18.258+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:37:18.267+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:37:18.267+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:37:18.268+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:37:18.268+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:37:18.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:37:18.273+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:37:58.246+0000] {processor.py:153} INFO - Started process (PID=67942) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:37:58.247+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:37:58.248+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:37:58.248+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:37:58.258+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:37:58.257+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:37:58.258+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:37:58.258+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:37:58.258+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:37:58.263+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:38:31.946+0000] {processor.py:153} INFO - Started process (PID=67989) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:38:31.947+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:38:31.947+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:38:31.947+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:38:31.957+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:38:31.957+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:38:31.957+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:38:31.957+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:38:31.957+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:38:31.963+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:39:07.301+0000] {processor.py:153} INFO - Started process (PID=68032) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:39:07.302+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:39:07.303+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:39:07.303+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:39:07.312+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:39:07.312+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:39:07.313+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:39:07.313+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:39:07.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:39:07.318+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:39:46.059+0000] {processor.py:153} INFO - Started process (PID=68081) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:39:46.060+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:39:46.060+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:39:46.060+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:39:46.071+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:39:46.070+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:39:46.071+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:39:46.071+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:39:46.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:39:46.076+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:40:21.491+0000] {processor.py:153} INFO - Started process (PID=68239) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:40:21.492+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:40:21.492+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:40:21.492+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:40:21.502+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:40:21.502+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:40:21.502+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:40:21.502+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:40:21.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:40:21.508+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:40:56.565+0000] {processor.py:153} INFO - Started process (PID=68284) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:40:56.566+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:40:56.566+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:40:56.566+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:40:56.576+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:40:56.576+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:40:56.576+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:40:56.576+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:40:56.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:40:56.582+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:41:35.758+0000] {processor.py:153} INFO - Started process (PID=68333) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:41:35.759+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:41:35.760+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:41:35.760+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:41:35.770+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:41:35.769+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:41:35.770+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:41:35.770+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:41:35.770+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:41:35.776+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:42:12.221+0000] {processor.py:153} INFO - Started process (PID=68407) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:42:12.222+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:42:12.223+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:42:12.223+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:42:12.233+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:42:12.232+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:42:12.233+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:42:12.233+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:42:12.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:42:12.239+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:42:50.841+0000] {processor.py:153} INFO - Started process (PID=68459) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:42:50.842+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:42:50.842+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:42:50.842+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:42:50.852+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:42:50.852+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:42:50.852+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:42:50.852+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:42:50.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:42:50.858+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:43:28.896+0000] {processor.py:153} INFO - Started process (PID=68504) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:43:28.897+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:43:28.898+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:43:28.897+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:43:28.907+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:43:28.907+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:43:28.907+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:43:28.907+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:43:28.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:43:28.913+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:44:12.759+0000] {processor.py:153} INFO - Started process (PID=68559) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:44:12.760+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:44:12.761+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:44:12.761+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:44:12.770+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:44:12.770+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:44:12.771+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:44:12.771+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:44:12.771+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:44:12.777+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:44:49.698+0000] {processor.py:153} INFO - Started process (PID=68602) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:44:49.699+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:44:49.700+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:44:49.700+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:44:49.709+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:44:49.709+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:44:49.709+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:44:49.709+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:44:49.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:44:49.715+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:45:33.904+0000] {processor.py:153} INFO - Started process (PID=68751) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:45:33.905+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:45:33.905+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:45:33.905+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:45:33.915+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:45:33.915+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:45:33.915+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:45:33.915+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:45:33.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:45:33.921+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:46:16.521+0000] {processor.py:153} INFO - Started process (PID=68810) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:46:16.522+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:46:16.522+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:46:16.522+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:46:16.532+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:46:16.532+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:46:16.532+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:46:16.532+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:46:16.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:46:16.538+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:46:54.859+0000] {processor.py:153} INFO - Started process (PID=68887) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:46:54.861+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:46:54.861+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:46:54.861+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:46:54.871+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:46:54.870+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:46:54.871+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:46:54.871+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:46:54.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:46:54.877+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:47:29.802+0000] {processor.py:153} INFO - Started process (PID=68930) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:47:29.803+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:47:29.803+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:47:29.803+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:47:29.813+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:47:29.813+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:47:29.813+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:47:29.813+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:47:29.813+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:47:29.820+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:48:09.430+0000] {processor.py:153} INFO - Started process (PID=68982) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:48:09.431+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:48:09.432+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:48:09.432+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:48:09.441+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:48:09.441+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:48:09.442+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:48:09.442+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:48:09.442+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:48:09.447+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:48:48.117+0000] {processor.py:153} INFO - Started process (PID=69029) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:48:48.118+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:48:48.119+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:48:48.118+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:48:48.129+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:48:48.128+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:48:48.129+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:48:48.129+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:48:48.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:48:48.134+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:49:27.586+0000] {processor.py:153} INFO - Started process (PID=69080) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:49:27.587+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:49:27.587+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:49:27.587+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:49:27.597+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:49:27.596+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:49:27.597+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:49:27.597+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:49:27.597+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:49:27.603+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:50:10.943+0000] {processor.py:153} INFO - Started process (PID=69197) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:50:10.945+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:50:10.945+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:50:10.945+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:50:10.955+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:50:10.955+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:50:10.955+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:50:10.955+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:50:10.955+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:50:10.961+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:50:45.160+0000] {processor.py:153} INFO - Started process (PID=69269) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:50:45.161+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:50:45.162+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:50:45.161+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:50:45.171+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:50:45.171+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:50:45.172+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:50:45.172+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:50:45.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:50:45.177+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:51:25.095+0000] {processor.py:153} INFO - Started process (PID=69320) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:51:25.096+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:51:25.097+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:51:25.097+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:51:25.107+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:51:25.106+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:51:25.107+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:51:25.107+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:51:25.107+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:51:25.113+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:52:06.202+0000] {processor.py:153} INFO - Started process (PID=69368) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:52:06.204+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:52:06.204+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:52:06.204+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:52:06.214+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:52:06.214+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:52:06.214+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:52:06.214+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:52:06.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:52:06.220+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:52:49.626+0000] {processor.py:153} INFO - Started process (PID=69414) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:52:49.627+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:52:49.627+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:52:49.627+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:52:49.637+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:52:49.637+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:52:49.637+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:52:49.637+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:52:49.637+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:52:49.643+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:53:24.718+0000] {processor.py:153} INFO - Started process (PID=69474) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:53:24.719+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:53:24.719+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:53:24.719+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:53:24.729+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:53:24.729+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:53:24.730+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:53:24.730+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:53:24.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:53:24.735+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:53:59.327+0000] {processor.py:153} INFO - Started process (PID=69515) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:53:59.328+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:53:59.329+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:53:59.329+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:53:59.339+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:53:59.338+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:53:59.339+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:53:59.339+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:53:59.339+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:53:59.345+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:54:37.565+0000] {processor.py:153} INFO - Started process (PID=69562) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:54:37.566+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:54:37.567+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:54:37.567+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:54:37.577+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:54:37.576+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:54:37.577+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:54:37.577+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:54:37.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:54:37.582+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:55:25.589+0000] {processor.py:153} INFO - Started process (PID=69686) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:55:25.591+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:55:25.591+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:55:25.591+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:55:25.601+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:55:25.600+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:55:25.601+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:55:25.601+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:55:25.601+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:55:25.607+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-04-27T00:56:07.939+0000] {processor.py:153} INFO - Started process (PID=69868) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:56:07.940+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:56:07.941+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:56:07.941+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:56:07.951+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:56:07.950+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:56:07.951+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:56:07.951+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:56:07.951+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:56:07.957+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:56:50.176+0000] {processor.py:153} INFO - Started process (PID=69995) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:56:50.177+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:56:50.178+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:56:50.178+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:56:50.188+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:56:50.188+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:56:50.188+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:56:50.188+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:56:50.188+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:56:50.195+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:57:29.025+0000] {processor.py:153} INFO - Started process (PID=70103) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:57:29.027+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:57:29.028+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:57:29.028+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:57:29.037+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:57:29.037+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:57:29.037+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:57:29.037+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:57:29.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:57:29.044+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:58:07.292+0000] {processor.py:153} INFO - Started process (PID=70222) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:58:07.293+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:58:07.294+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:58:07.294+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:58:07.304+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:58:07.304+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:58:07.304+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:58:07.304+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:58:07.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:58:07.311+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:58:47.125+0000] {processor.py:153} INFO - Started process (PID=70277) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:58:47.126+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:58:47.127+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:58:47.127+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:58:47.137+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:58:47.136+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:58:47.137+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:58:47.137+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:58:47.137+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:58:47.143+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T00:59:27.989+0000] {processor.py:153} INFO - Started process (PID=70342) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:59:27.990+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T00:59:27.991+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:59:27.990+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:59:28.001+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:59:28.000+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T00:59:28.001+0000] {logging_mixin.py:137} INFO - [2023-04-27T00:59:28.001+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T00:59:28.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T00:59:28.007+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T03:25:21.703+0000] {processor.py:153} INFO - Started process (PID=73620) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:25:21.704+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:25:21.704+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:25:21.704+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:25:21.715+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:25:21.714+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:25:21.715+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:25:21.715+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:25:21.715+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:25:21.721+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T03:26:05.309+0000] {processor.py:153} INFO - Started process (PID=73693) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:26:05.310+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:26:05.310+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:26:05.310+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:26:05.320+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:26:05.320+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:26:05.321+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:26:05.321+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:26:05.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:26:05.327+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T03:26:49.872+0000] {processor.py:153} INFO - Started process (PID=73883) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:26:49.873+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:26:49.874+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:26:49.873+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:26:49.884+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:26:49.884+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:26:49.884+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:26:49.884+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:26:49.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:26:49.890+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T03:27:32.868+0000] {processor.py:153} INFO - Started process (PID=73928) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:27:32.869+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:27:32.870+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:27:32.870+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:27:32.880+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:27:32.880+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:27:32.880+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:27:32.880+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:27:32.881+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:27:32.887+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T03:28:13.402+0000] {processor.py:153} INFO - Started process (PID=73983) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:28:13.403+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:28:13.404+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:28:13.404+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:28:13.414+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:28:13.414+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:28:13.414+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:28:13.414+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:28:13.414+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:28:13.420+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T03:28:50.737+0000] {processor.py:153} INFO - Started process (PID=74030) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:28:50.738+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:28:50.739+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:28:50.739+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:28:50.749+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:28:50.749+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:28:50.750+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:28:50.750+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:28:50.750+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:28:50.756+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T03:29:33.512+0000] {processor.py:153} INFO - Started process (PID=74071) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:29:33.513+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:29:33.514+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:29:33.514+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:29:33.525+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:29:33.524+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:29:33.525+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:29:33.525+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:29:33.525+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:29:33.531+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T03:30:16.787+0000] {processor.py:153} INFO - Started process (PID=74256) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:30:16.788+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:30:16.789+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:30:16.789+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:30:16.799+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:30:16.799+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:30:16.799+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:30:16.799+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:30:16.799+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:30:16.914+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.129 seconds
[2023-04-27T03:30:59.885+0000] {processor.py:153} INFO - Started process (PID=74356) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:30:59.886+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:30:59.887+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:30:59.887+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:30:59.897+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:30:59.897+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:30:59.897+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:30:59.897+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:30:59.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:30:59.904+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T03:31:42.115+0000] {processor.py:153} INFO - Started process (PID=74404) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:31:42.116+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:31:42.117+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:31:42.117+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:31:42.127+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:31:42.127+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:31:42.127+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:31:42.127+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:31:42.128+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:31:42.134+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T03:32:27.016+0000] {processor.py:153} INFO - Started process (PID=74449) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:32:27.017+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:32:27.018+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:32:27.018+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:32:27.028+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:32:27.027+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:32:27.028+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:32:27.028+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:32:27.028+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:32:27.034+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-04-27T03:33:11.482+0000] {processor.py:153} INFO - Started process (PID=74498) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:33:11.483+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:33:11.483+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:33:11.483+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:33:11.494+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:33:11.493+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:33:11.494+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:33:11.494+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:33:11.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:33:11.606+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2023-04-27T03:33:42.750+0000] {processor.py:153} INFO - Started process (PID=74531) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:33:42.751+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:33:42.751+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:33:42.751+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:33:42.869+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:33:42.868+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:33:42.869+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:33:42.869+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:33:42.869+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:33:42.874+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2023-04-27T03:34:25.936+0000] {processor.py:153} INFO - Started process (PID=74582) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:34:25.938+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:34:25.938+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:34:25.938+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:34:25.948+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:34:25.948+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:34:25.948+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:34:25.948+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:34:25.949+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:34:25.955+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-04-27T03:35:00.792+0000] {processor.py:153} INFO - Started process (PID=74622) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:35:00.793+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-27T03:35:00.793+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:35:00.793+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:35:00.804+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:35:00.803+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-27T03:35:00.804+0000] {logging_mixin.py:137} INFO - [2023-04-27T03:35:00.804+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-27T03:35:00.804+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-27T03:35:00.810+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
